import type { AnalysisResult } from "@/types/analysis";
import type { CarListingInput } from "@/types/car";

/**
 * Realistisk demo/seed-data så att appen går att testa end-to-end
 * innan Supabase/Claude är kopplat. Tydligt taggad `isDemo: true`.
 */

function listing(partial: Partial<CarListingInput>): CarListingInput {
  return {
    sourceType: "manual",
    sourceUrl: null,
    make: null,
    model: null,
    modelYear: null,
    mileageKm: null,
    fuelType: null,
    gearbox: null,
    engine: null,
    powerHp: null,
    price: null,
    ownerCount: null,
    serviceHistoryNotes: null,
    equipment: [],
    description: null,
    imageUris: [],
    region: null,
    ...partial,
  };
}

export const demoAnalyses: AnalysisResult[] = [
  {
    id: "demo_volvo_v60",
    createdAt: "2026-08-20T09:12:00.000Z",
    isDemo: true,
    listing: listing({
      sourceType: "blocket",
      sourceUrl: "https://www.blocket.se/annons/exempel-volvo-v60",
      make: "Volvo",
      model: "V60 D4",
      modelYear: 2018,
      mileageKm: 142000,
      fuelType: "diesel",
      gearbox: "automat",
      engine: "2.0 D4",
      powerHp: 190,
      price: 154900,
      ownerCount: 2,
      serviceHistoryNotes: "Servad på Volvo-verkstad, senaste service vid 138 000 km.",
      equipment: ["Skinnklädsel", "Navigation", "Adaptiv farthållare", "Dragkrok"],
      description: "Välskött V60 med fullständig servicehistorik. Nya däck fram och bak.",
      region: "Stockholm",
    }),
    verdict: "good_buy",
    confidence: 0.86,
    priceAssessment: {
      listedPrice: 154900,
      estimatedMarketMin: 148000,
      estimatedMarketMax: 168000,
      assessment: "fair",
      confidenceNote: null,
    },
    risks: [
      { key: "service_history", label: "Servicehistorik", level: "low", note: "Komplett historik i annonsen." },
      { key: "mileage", label: "Miltal", level: "low", note: "Normalt för årsmodell och ålder." },
      { key: "price", label: "Pris", level: "low", note: "Ligger inom marknadsintervallet." },
      { key: "owner_history", label: "Ägarhistorik", level: "low", note: "Två tidigare ägare, inga anmärkningar." },
      { key: "listing_information", label: "Annonsinformation", level: "low", note: "Utförlig och konsekvent annons." },
    ],
    missingInformation: ["Besiktningsprotokoll", "Exakt datum för senaste kamremsbyte"],
    recommendedChecks: [
      "Be om dokumentation för senaste besiktning.",
      "Kontrollera datum för kamremsbyte (D4-motorn har rem, inte kedja).",
      "Provkör och lyssna efter ovanliga ljud vid kallstart.",
    ],
    negotiation: {
      recommendedOffer: 148000,
      targetPriceMin: 148000,
      targetPriceMax: 152000,
      arguments: [
        "Miltalet är i högre delen av spannet för årsmodellen.",
        "Kamremsbyte saknar dokumenterat datum, vilket är en kommande kostnad.",
        "Liknande bilar i regionen ligger på samma nivå eller lägre.",
      ],
    },
    summary:
      "Priset ligger i linje med marknadsvärdet och servicehistoriken är väl dokumenterad. Inga tydliga varningssignaler, men be om underlag för kamremsbyte innan köp.",
  },
  {
    id: "demo_bmw_320d",
    createdAt: "2026-08-18T14:40:00.000Z",
    isDemo: true,
    listing: listing({
      sourceType: "blocket",
      sourceUrl: "https://www.blocket.se/annons/exempel-bmw-320d",
      make: "BMW",
      model: "320d",
      modelYear: 2019,
      mileageKm: 124000,
      fuelType: "diesel",
      gearbox: "automat",
      engine: "2.0d",
      powerHp: 190,
      price: 149000,
      ownerCount: null,
      serviceHistoryNotes: null,
      equipment: ["M-sport", "Navigation", "Backkamera"],
      description: "Fin 320d M-sport. Nyservad. Inga kända fel.",
      region: "Göteborg",
    }),
    verdict: "caution",
    confidence: 0.71,
    priceAssessment: {
      listedPrice: 149000,
      estimatedMarketMin: 138000,
      estimatedMarketMax: 155000,
      assessment: "fair",
      confidenceNote: null,
    },
    risks: [
      { key: "service_history", label: "Servicehistorik", level: "medium", note: "\"Nyservad\" är inte dokumenterat med kvitto eller datum." },
      { key: "mileage", label: "Miltal", level: "low", note: "Rimligt för årsmodellen." },
      { key: "price", label: "Pris", level: "low", note: "Inom marknadsintervallet." },
      { key: "owner_history", label: "Ägarhistorik", level: "medium", note: "Antal ägare anges inte i annonsen." },
      { key: "listing_information", label: "Annonsinformation", level: "high", note: "Kort beskrivning utan detaljer om skador eller historik." },
    ],
    missingInformation: ["Antal tidigare ägare", "Servicekvitton", "Besiktningshistorik"],
    recommendedChecks: [
      "Be om dokumentation för senaste service.",
      "Kontrollera kamkedja — tidiga B47-motorer har haft kända kamkedjeproblem.",
      "Kontrollera tidigare skador via besiktningsprotokoll.",
    ],
    negotiation: {
      recommendedOffer: 138000,
      targetPriceMin: 140000,
      targetPriceMax: 143000,
      arguments: [
        "Servicehistoriken är inte dokumenterad, vilket ökar risken.",
        "Antal ägare saknas i annonsen och bör klargöras.",
        "Annonsen ger begränsad information jämfört med liknande objekt.",
      ],
    },
    summary:
      "Priset ligger inom rimligt intervall, men annonsen saknar viktig dokumentation kring service och ägarhistorik. Verifiera underlag innan du går vidare.",
  },
  {
    id: "demo_audi_a4",
    createdAt: "2026-08-12T11:05:00.000Z",
    isDemo: true,
    listing: listing({
      sourceType: "wayke",
      sourceUrl: "https://www.wayke.se/annons/exempel-audi-a4",
      make: "Audi",
      model: "A4 Avant",
      modelYear: 2017,
      mileageKm: 186000,
      fuelType: "diesel",
      gearbox: "manuell",
      engine: "2.0 TDI",
      powerHp: 150,
      price: 159000,
      ownerCount: 3,
      serviceHistoryNotes: "Delvis dokumenterad, saknar kvitton för de senaste två åren.",
      equipment: ["Xenon", "Farthållare"],
      description: "A4 Avant i gott skick. Några repor i lacken. Säljs i befintligt skick.",
      region: "Malmö",
    }),
    verdict: "avoid",
    confidence: 0.78,
    priceAssessment: {
      listedPrice: 159000,
      estimatedMarketMin: 118000,
      estimatedMarketMax: 138000,
      assessment: "expensive",
      confidenceNote: null,
    },
    risks: [
      { key: "service_history", label: "Servicehistorik", level: "high", note: "Två års luckor i dokumentationen." },
      { key: "mileage", label: "Miltal", level: "medium", note: "Högt miltal för årsmodellen." },
      { key: "price", label: "Pris", level: "high", note: "Cirka 15–20 % över uppskattat marknadsvärde." },
      { key: "owner_history", label: "Ägarhistorik", level: "medium", note: "Tre ägare på sju år." },
      { key: "listing_information", label: "Annonsinformation", level: "medium", note: "\"Befintligt skick\" och nämnda repor kräver närmare granskning." },
    ],
    missingInformation: ["Servicekvitton 2024–2026", "Bilder på angivna skador"],
    recommendedChecks: [
      "Be om samtliga servicekvitton, särskilt de senaste två åren.",
      "Besikta lacken och underredet för dolda skador.",
      "Jämför pris mot minst tre liknande annonser innan bud.",
    ],
    negotiation: {
      recommendedOffer: 120000,
      targetPriceMin: 122000,
      targetPriceMax: 130000,
      arguments: [
        "Priset ligger klart över uppskattat marknadsvärde för miltal och årsmodell.",
        "Servicehistoriken har dokumenterade luckor.",
        "Kosmetiska skador nämns men är inte specificerade.",
        "Tre tidigare ägare ökar osäkerheten kring bilens historik.",
      ],
    },
    summary:
      "Priset ligger märkbart över marknadsvärdet och servicehistoriken har luckor. I nuvarande skick och pris rekommenderar vi att avstå — eller förhandla ner priset avsevärt.",
  },
  {
    id: "demo_toyota_rav4",
    createdAt: "2026-08-05T16:22:00.000Z",
    isDemo: true,
    listing: listing({
      sourceType: "manual",
      sourceUrl: null,
      make: "Toyota",
      model: "RAV4 Hybrid",
      modelYear: 2021,
      mileageKm: 61000,
      fuelType: "hybrid",
      gearbox: "automat",
      engine: "2.5 Hybrid",
      powerHp: 218,
      price: 289000,
      ownerCount: 1,
      serviceHistoryNotes: "Komplett historik hos auktoriserad Toyota-verkstad.",
      equipment: ["Adaptiv farthållare", "360-kamera", "Skinn/textil", "Dragkrok"],
      description: "En ägare sedan ny. Fullservad. Inga anmärkningar vid senaste besiktning.",
      region: "Uppsala",
    }),
    verdict: "good_buy",
    confidence: 0.91,
    priceAssessment: {
      listedPrice: 289000,
      estimatedMarketMin: 275000,
      estimatedMarketMax: 298000,
      assessment: "fair",
      confidenceNote: null,
    },
    risks: [
      { key: "service_history", label: "Servicehistorik", level: "low", note: "Fullständig och verifierbar." },
      { key: "mileage", label: "Miltal", level: "low", note: "Lågt för årsmodellen." },
      { key: "price", label: "Pris", level: "low", note: "Väl inom marknadsintervallet." },
      { key: "owner_history", label: "Ägarhistorik", level: "low", note: "En ägare sedan ny." },
      { key: "listing_information", label: "Annonsinformation", level: "low", note: "Detaljerad och konsekvent." },
    ],
    missingInformation: [],
    recommendedChecks: [
      "Kontrollera hybridbatteriets hälsostatus vid provkörning.",
      "Verifiera VIN mot registreringsbevis.",
      "Kontrollera senaste besiktningsprotokoll.",
    ],
    negotiation: {
      recommendedOffer: 279000,
      targetPriceMin: 279000,
      targetPriceMax: 285000,
      arguments: [
        "Bilen är prissatt i linje med marknaden, så förhandlingsutrymmet är begränsat.",
        "En mindre justering är rimlig givet kontantköp.",
      ],
    },
    summary:
      "En av de mest välskötta bilarna vi sett i den här klassen — komplett historik, en ägare och rimligt pris. Låg risk och gott köp.",
  },
];

export function getDemoAnalysisById(id: string): AnalysisResult | undefined {
  return demoAnalyses.find((a) => a.id === id);
}
